apiVersion: v1
kind: Pod
metadata:
  name: podwithvolumes
spec:
      containers:
      - name: busyboxcontainer
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        volumeMounts:
        - mountPath: /shareddir
          name: share-volume

      - name: redis
        image: redis
        volumeMounts:
        - mountPath: /shareddir
          name: share-volume

      volumes:
      - name: share-volume
        emptyDir: {}
