apiVersion: v1
kind: Pod
metadata:
  name: achen-podwith2containers
spec:
      containers:
      - name: busyboxcontainer
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']

      - name: redis
        image: redis
