apiVersion: v1 
kind: Service 
metadata: 
    name: nginxwebexternal 
spec: 
   selector: 
     web: nginx 
   type: NodePort
   ports: 
        - protocol: TCP 
          port: 80 
          targetPort: 80
