apiVersion: v1
kind: Pod
metadata:
  name: nodeselectpod
spec:
  containers:
    - name: hello
      image: busybox
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
  nodeSelector:
      nodecpu: amd
